# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - DataScienceBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Nodejs project
    runs-on: windows-latest
    defaults:
      run:
        # Mobile folder working directory.
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    defaults:
      run:
        # Mobile folder working directory.
        working-directory: api

    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'

      - name: Download artifact from build job
        if: steps.filter.outputs.api == 'true'
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        if: steps.filter.outputs.api == 'true'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "DataScienceBackend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CEB31279AE6949A1981CB4A4749D603F }}
          package: .
